if(NOT DEFINED ACS_WHISPER_MODEL_URL OR ACS_WHISPER_MODEL_URL STREQUAL "")
  message(FATAL_ERROR "ACS_WHISPER_MODEL_URL is required")
endif()
if(NOT DEFINED ACS_WHISPER_MODEL_DIR OR ACS_WHISPER_MODEL_DIR STREQUAL "")
  message(FATAL_ERROR "ACS_WHISPER_MODEL_DIR is required")
endif()
if(NOT DEFINED ACS_WHISPER_MODEL_NAME OR ACS_WHISPER_MODEL_NAME STREQUAL "")
  message(FATAL_ERROR "ACS_WHISPER_MODEL_NAME is required")
endif()
if(NOT DEFINED ACS_WHISPER_MODEL_STAMP OR ACS_WHISPER_MODEL_STAMP STREQUAL "")
  message(FATAL_ERROR "ACS_WHISPER_MODEL_STAMP is required")
endif()

set(model_root "${ACS_WHISPER_MODEL_DIR}")
set(model_file "${ACS_WHISPER_MODEL_DIR}/${ACS_WHISPER_MODEL_NAME}")

if(EXISTS "${model_file}")
  message(STATUS "Whisper model already present at ${model_file}")
  file(TOUCH "${ACS_WHISPER_MODEL_STAMP}")
  return()
endif()

file(MAKE_DIRECTORY "${model_root}")
message(STATUS "Downloading model from ${ACS_WHISPER_MODEL_URL}")
file(DOWNLOAD "${ACS_WHISPER_MODEL_URL}" "${model_file}" SHOW_PROGRESS STATUS dl_status TLS_VERIFY ON)
list(GET dl_status 0 dl_code)
list(GET dl_status 1 dl_msg)
if(NOT dl_code EQUAL 0)
  message(FATAL_ERROR "Model download failed (${dl_code}): ${dl_msg}")
endif()

file(TOUCH "${ACS_WHISPER_MODEL_STAMP}")
